// Package iap classifies upstream responses as IAP-origin auth failures
// vs. application responses, and produces actionable error messages.
package iap

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// generatedHeader is set by IAP on every response it generates itself,
// distinguishing IAP-origin errors from app-origin errors.
const generatedHeader = "X-Goog-Iap-Generated-Response"

// IsIAPResponse reports whether the response was generated by IAP
// itself rather than the upstream application.
func IsIAPResponse(resp *http.Response) bool {
	return strings.EqualFold(resp.Header.Get(generatedHeader), "true")
}

// IsAuthFailure reports whether the response is an IAP authentication
// failure: a 401, or a 302 redirect into the Google sign-in flow (which
// IAP issues when the token is absent or malformed).
func IsAuthFailure(resp *http.Response) bool {
	switch resp.StatusCode {
	case http.StatusUnauthorized:
		return true
	case http.StatusFound, http.StatusMovedPermanently, http.StatusSeeOther, http.StatusTemporaryRedirect:
		return isGoogleSignInRedirect(resp)
	}
	return false
}

func isGoogleSignInRedirect(resp *http.Response) bool {
	loc, err := url.Parse(resp.Header.Get("Location"))
	if err != nil {
		return false
	}
	return strings.EqualFold(loc.Host, "accounts.google.com")
}

// ActionableMessage renders a one-line, actionable description of an
// IAP auth/authz failure, suitable for stderr. It peeks at up to 4 KiB
// of the response body to look for IAP's error text, then reattaches
// what it read so later readers still see the full body.
func ActionableMessage(resp *http.Response, audience string) string {
	body := peekBody(resp, 4<<10)

	switch {
	case resp.StatusCode == http.StatusUnauthorized && strings.Contains(strings.ToLower(body), "audience"):
		return fmt.Sprintf("audience mismatch: token aud=%s but IAP rejected it; for load-balancer IAP pass --audience <NNN>.apps.googleusercontent.com (the IAP OAuth client ID)", audience)
	case resp.StatusCode == http.StatusUnauthorized:
		return fmt.Sprintf("IAP rejected the ID token (aud=%s): verify the audience and that the token is a Google-issued OIDC ID token (IAP said: %s)", audience, firstLine(body))
	case resp.StatusCode == http.StatusForbidden && IsIAPResponse(resp):
		return "permission denied: grant roles/iap.httpsResourceAccessor to the calling principal on the IAP resource"
	case IsAuthFailure(resp):
		return fmt.Sprintf("IAP redirected to Google sign-in (token absent or malformed); check credentials and --audience (current aud=%s)", audience)
	default:
		return fmt.Sprintf("upstream returned HTTP %d: %s", resp.StatusCode, firstLine(body))
	}
}

// peekBody reads up to n bytes of the response body and reassembles
// resp.Body so the caller's downstream readers see the complete body.
func peekBody(resp *http.Response, n int64) string {
	if resp.Body == nil {
		return ""
	}
	b, _ := io.ReadAll(io.LimitReader(resp.Body, n))
	resp.Body = &prefixedBody{prefix: bytes.NewReader(b), rest: resp.Body}
	return string(b)
}

type prefixedBody struct {
	prefix *bytes.Reader
	rest   io.ReadCloser
}

func (p *prefixedBody) Read(b []byte) (int, error) {
	if p.prefix.Len() > 0 {
		return p.prefix.Read(b)
	}
	return p.rest.Read(b)
}

func (p *prefixedBody) Close() error { return p.rest.Close() }

func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if len(s) > 200 {
		s = s[:200] + "..."
	}
	if s == "" {
		return "(empty body)"
	}
	return s
}
